### ISSUE TITLE
Place disambiguation

### ISSUE THREAD

**Issue by dlschwartz** [srophe/syriaca-data#1052]
There are ca. 35 instances of `<note type="disambiguation">` in places and ca. 26 instances in persons. I will convert these to the following format:

```
<relation type="disambiguation" ref="http://syriaca.org/keyword/different-from" active="http://syriaca.org/person/####" passive="http://syriaca.org/person/####" source="#bib####-#">
    <desc xml:lang="en">[Add text from current note element here]</desc>
</relation>
```

_Originally posted by @dlschwartz in https://github.com/srophe/srophe-app-data/issues/1030#issuecomment-1589618791_

**Comment by dlschwartz** [comment]
Some place records have `<note type="disambiguation">` and `<relation name="share-a-name">`. 

In place/571, this is a duplication of data where both elements distinguish place/571 from place/343. Same with place/343, place/298, place/2532

But, in see also [place/712#L112](https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/712.xml#L112) and #L122. Here they don't deal with the same place. Same with place/551, place/346, place/130, place/111.

We definitely want to avoid duplicating data. But what value should we use? I propose we deprecate "share-a-name" and instead follow the new/evolving persons model and use `<relation ref="http://syriaca.org/keyword/different-from".

Also, in six place records (88, 94, 114, 377, 632, 2566) we get a note that distinguishes this entity from a pleiades URI.

In one pair of records, place/114 and place/2566, we have a syriaca.org record that contains the pleiades URI as a tei:idno. In this case, we should simply create tei:relation elements in each record that indicate that these syriaca.org URIs are "different-from" each other.

In four other cases, there is no syriaca.org place record that contains a tei:idno linking our entity to the pleiades entity. [I was unable to try fuzzy search b/c the site was down.]
- place/377 contains http://pleiades.stoa.org/places/874439 (Cyriacus, Mon.) = n/a
- place/632 contains http://pleiades.stoa.org/places/952097 (Parthyene/Parthia) =? http://syriaca.org/place/632 
- [place/88](https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/88.xml#L176) contains http://pleiades.stoa.org/places/874296 (Ad flumen Tigram) = n/a
- place/94 contains http://pleiades.stoa.org/places/658574 (Pordonnium) = n/a

**Comment by dlschwartz** [comment]
And finally, we need to develop a system of relationships between cities, regions around cities, diocese associated with cities.

**Comment by wlpotter** [comment]
A few thoughts on this:

1. I agree with moving to using relations rather than notes for these cases. I do wonder, though, if it's worth keeping "share-a-name" as a narrower concept than "different-from"? The case of place/712 seems like a good example where we want to say more broadly that [Gazarta](https://syriaca.org/place/712) and [Upper Jazira/Diyar Rabi'a](https://syriaca.org/place/321) are different, even though they don't share a name.
2. I'm not sure how I feel about disambiguating our places against Pleiades (the examples of 88, 94, 114, etc.). In the case of [88](https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/88.xml#L176), for example, I'm not sure why the Pleiades URI is even referenced if they are different conceptual places?
3. I agree that have a more explicit system of relating cities, regions, diocese would be useful so as not to rely on somewhat opaque share-a-name and different-from relations

**Comment by davidamichelson** [comment]
Okay, thanks @wlpotter Dan and I met and agree on your points 1 and 2.

Here are the relationship names we will use going forward, with no sub-typing.

share a name
share a location
conceptually related
contained by
should not be confused with

**Comment by davidamichelson** [comment]
For point three (use of Pleiades URIs), we can keep these because there will always be cases where we want to disambiguate against external URIS for places or persons for whom we would never create a Syriaca URI. For example, in the case of [Syriaca.org place/88](https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/88.xml#L176) we want to assert that it is not the same as this Roman camp mentioned in Pleiades http://pleiades.stoa.org/places/874296 (Ad flumen Tigram) because if in the future someone tries to match our place with Pleiades, they may find that place and try and match it, but we have already spent time to disambiguate it. We may want to adjust how non Syriaca URIs are displayed, perhaps they are suppressed currently in the relationship side bar. We may want to edit the prose of the note.

**Comment by dlschwartz** [comment]
The possible place relationships should be the following:
```
<relation type="disambiguation" ref="http://syriaca.org/keyword/conceptually-related" mutual="#1 #2">
<relation type="disambiguation" ref="http://syriaca.org/keyword/co-located" mutual="#1 #2">
<relation type="disambiguation" ref="http://syriaca.org/keyword/not-to-be-confused-with" mutual="#1 #2">
<relation type="disambiguation" ref="http://syriaca.org/keyword/share-a-name" mutual="#1 #2">
<relation type="contained-within" ref="http://www.w3.org/2004/02/skos/core#broader" active="#1" passive="#2">
<relation type="see-also" ref="http://www.w3.org/2004/02/skos/core#related" mutual="#1 #2">

```

**Comment by wlpotter** [comment]
Thanks @davidamichelson  and @dlschwartz these all look great!

**Comment by dlschwartz** [comment]
The commit above establishes these changes in the schema (oops, just noticed my commit message says persons but it's actually places)

**Comment by dlschwartz** [comment]
The above commits (as well as [this one that I forgot to link](https://github.com/srophe/syriaca-data/commit/a97a51a47e840886a1b9323c9099b406f403217d)) implement these change to place disambiguation.
